/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "category",
      label: "Choose your standards",
      link: {
        type: "doc",
        id: "index",
      },
      collapsible: true,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "standards" }],
    },
    // {
    //   type: "html",
    //   value: "<h4 class='custom-doc-header'>The tools</h4>", // The HTML to be rendered
    //   defaultStyle: false, // Use the default menu item styling
    // },
  ],
};

module.exports = sidebar;
